packageExtensions:
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '^8.0.3'
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20230217.hash-56aa982.cjs
